### ISSUE TITLE
1.20.2 Compatibility?

### ISSUE THREAD

**Issue by Jackuhlf** [malte0811/FerriteCore#133]
Usually this mod is really good about updating to new versions. When will this mod work for 1.20.2?

**Comment by malte0811** [comment]
- On Fabric/Quilt the 1.20.0/1 build works. I've marked it as such on CF but forgot it on MR, I will do that now. If you run into problems, please open issues for them specifically.
- On the \*Forge side: NeoForge is not yet available on 1.20.2, and I do not intend to support LexForge.

In general it is not considered polite to ask for ETAs on mod updates. Quite often it's simply because the dev has other commitments IRL (work, studies, etc) and has not found time to update yet.
