### ISSUE TITLE
No Mod Icon

### ISSUE THREAD

**Issue by DragonEggBedrockBreaking** [malte0811/FerriteCore#14]
There is no mod icon for modmenu. Maybe add the same icon as the icon you used on modrinth?

**Comment by Felix14-v2** [comment]
Maybe like [this](https://i.pinimg.com/originals/04/f7/0c/04f70cf3a3b06576f040c2682d8f15df.jpg)?

**Comment by malte0811** [comment]
I'll look into adding an icon when I make a new release; I probably won't use any of the "usual" images, since they would drastically increase the size of the jar (currently 86 kB). My current idea is to use the [hysteresis curve](https://upload.wikimedia.org/wikipedia/commons/5/5b/Ringkernspeicher_hysteresekurven.agr.png) of a ferrite core which should compress much better, but I'm not entirely sure yet. In any case I won't make a release just for this, so it won't happen until someone either finds a bug or I (or maybe someone else) find(s) a new optimization to implement in FC.

**Comment by malte0811** [comment]
Fixed in version 2.0.5 (I just forgot to close this).
