### ISSUE TITLE
this is outrageous!

### ISSUE THREAD

**Issue by LotP1** [malte0811/FerriteCore#16]
This is a giant issue that's really been bugging me while i've been playing with this...
How hasn't Mojang hired you yet?

**Comment by malte0811** [comment]
Thanks, but a) I don't think they'd hire me, b) I would not want to move to Sweden and c) even without the first two, I don't think I'd want to work there. Not because of bad working conditions (they're actually quite good from what I've heard) or anything similar, I just would not want to turn my hobby into my job.

Also, FC is not actually that impressive code-wise. A lot of it is pretty simple, it just takes time looking at heapdumps, sifting through things that can't be improved and then improving the things that can be improved.
