### ISSUE TITLE
UnsupportedOperationException with SimpleStorageNetwork 1.7.0 (1.18.2 Forge)

### ISSUE THREAD

**Issue by LordDarthDan** [malte0811/FerriteCore#160]
When running my pack with that version of SSN, I get a crash with UnsupportedOperationException: "A mod tried to access the state neighbor table directly."

Reporting here as that's what the log suggested.

MC version: 1.18.2 Forge
Forge version: 40.2.18
FerriteCore version: 4.2.2
Simple Storage Network version: 1.7.0

Log: https://mclo.gs/YQs06Rd

(Note: the issue does not appear with Simple Storage Network version 1.6.2)

**Comment by malte0811** [comment]
You need to update JEI. The problem is this: Simple Storage Network wants a newer JEI version than you have. This causes Forge to stop loading mods, but not completely (in a certain sense). Canary has some code that is incompatible with FerriteCore, that they disable when FerriteCore is detected. BUT the detection does not work if there has been a dependency issue, even though the code still runs. So the code runs, thinks FerriteCore is not present (even though it is in the sense that is relevant here), and crashes because it is incompatible with FC.
