### ISSUE TITLE
Version 3.0.2 seems to break entity cramming.

### ISSUE THREAD

**Issue by sjm7** [malte0811/FerriteCore#33]
I'm using FerriteCore Fabric with Carpet, Lithium, Starlight, and Graves on a server. No settings regarding entity cramming or collisions were changed either in the vanilla gamerules or Carpet. A zombie piglin farm which used entity cramming with minecarts did not work with version 3.0.2, and reverting to 3.0.1 fixed it.

**Comment by malte0811** [comment]
Please double-check that the problem is actually the FerriteCore update from 3.0.1 to 3.0.2. The only functional difference between those builds is on the client, and even the mostly cosmetic server-side difference is not in any way related to entity cramming. If you are sure it's caused by this update please provide a world for me to test with, I know nothing about vanilla mob farms.
