### ISSUE TITLE
Crash with current development snapshot of lithium

### ISSUE THREAD

**Issue by Athemis** [malte0811/FerriteCore#50]
I was testing the impact of some current changes in lithium (tested with lithium at commit d11e2e8) on my server setup (MC 1.18.1, FerriteCore 4.0.0; full set of loaded mods and versions see attached log) which led to a crash related to some mod trying to access the state neighbor table directly. Using the latest release version of lithium does however start up without any issues. Hence lithium is the probable offender here.

 I was wondering if I should report this to lithium upstream instead, but the crashlog explicitly stated to file a bug report here.

[logfile: https://mclo.gs/ZbO2cyR](https://mclo.gs/ZbO2cyR)

**Comment by malte0811** [comment]
Disable `mixin.alloc.blockstate` in the lithium config for now (see the wiki of the lithium GH repo for details). The blockstate neighbor table optimizations from Hydrogen were recently moved into Lithium; so I need to remove my hydrogen compat (as H is discontinued) and replace it with lithium compat (much easier, since compat now simply means applying that config option automatically). I'll try to get a release out this weekend, but can't promise anything.

**Comment by Athemis** [comment]
Ok, thanks! I already set the option in FerriteCore to populate the state neighbour table. Worked as well.

**Comment by malte0811** [comment]
Fixed in 4.1.0:  
https://www.curseforge.com/minecraft/mc-mods/ferritecore-fabric/files/3637902  
https://modrinth.com/mod/ferrite-core/version/1FrNtQTK
