### ISSUE TITLE
FerritCore v4.1.1 crashes the game on launch

### ISSUE THREAD

**Issue by Scarlaid** [malte0811/FerriteCore#58]
Updated the mod to the lastest one using [this](https://modrinth.com/mod/modmanager) to v4.1.1
After a relaunch the game just crashed

I have enable `populateNeighborTable` in the `mixin.json`, sadly with the current lastest version it just crashed on any launch attempts
Using an older version, e.g v4.0.0 works fine

![image](https://user-images.githubusercontent.com/90851437/153793350-3d39f863-0a75-41b1-a173-3060a6290f21.png)

**Comment by malte0811** [comment]
FerriteCore is no longer compatible with Hydrogen in 1.18.1, since Hydrogen has been officially [discontinued](https://github.com/CaffeineMC/hydrogen-fabric/#january-23rd-2022) by Caffeine/Jelly. I'll keep this issue open as a reminder for myself to add an explicit incompatibility to the `fabric.mod.json`.

**Comment by Pekgame** [comment]
I have the same problem! So, do I need to use FerriteCore 4.1.0 instead?

**Comment by Pekgame** [comment]
You can easily fix it by using FerriteCore version 4.0.0 or lower!
