### ISSUE TITLE
Incompatible with Origins

### ISSUE THREAD

**Issue by jeffboy70** [malte0811/FerriteCore#59]
FerriteCore is incompatible with the Origins Fabric mod, it just crashes when you try to launch them together.

Origins 1.3.1
FerriteCore 4.0.0

Crash Log: https://paste.ee/p/XEN8f

**Comment by malte0811** [comment]
It launches fine for me with just Origins (plus dependencies) and FerriteCore. You have a lot of additional mods installed, can you try narrowing it down further? Alternatively, is your current set of mods available as a modpack on CF?

**Comment by malte0811** [comment]
Closing due to lack of response.

**Comment by dandin87** [comment]
I actually just got this same issue when i was helping someone try to add Origins to our All of Fabric 5 modpack. Removing Ferrite Core allows it to not crash. 

The first line blames biome makeover however removing it just has it fail because of expanded storage and I imagine it keeps on going like that.

https://aofpaste.com/noceyilayu.yaml

**Comment by dandin87** [comment]
So this is also a similar issue with Impersonate (jar in jar'd by bewitchment) and Origins but only when added to All of Fabric 5. As Ferrite Core, Bewitchment and Origins together, outside of the modpack, seems to work just fine.

**Comment by malte0811** [comment]
I've had a few cases of this before, the mod mentioned in the stacktrace is not at all related to the mod that caused it. As far as I know the only way to debug this is to attach a debugger/IDE to the modpack and check where `Identifier`/`ResourceLocation` is loaded. In this case it's a bug in ShowMeWhatYouGot, triggered by adding origins since that JiJs an old version of Calio, and the problematic code only runs when an old version of Calio is detected. See apace100/show-me-what-you-got#3.
