### ISSUE TITLE
Is this necessary with 5G++ alocated Java RAM?

### ISSUE THREAD

**Issue by ardissaps** [malte0811/FerriteCore#75]
Is this necessary with 5G++ alocated Java RAM? Also recently there is a mod that claim fix memory leak, is that true? And how related with FerriteCore either already did same thing or need both. Thx in advance

**Comment by malte0811** [comment]
> Is this necessary with 5G++ alocated Java RAM?

That depends on what other mods you have installed. If you have enough mods to make allocating 5GB necessary I'd recommend using FC in any case, it will probably get it down to 2-3 GB or even less.

> Also recently there is a mod that claim fix memory leak, is that true?

I haven't heard about this mod, so I can't answer that.

> And how related with FerriteCore either already did same thing or need both

FC does not fix any memory leaks since I'm not aware of any (relevant) ones; so you should probably use both, assuming that the leak fix mod actually fixes a relevant leak.

**Comment by ardissaps** [comment]
> > Is this necessary with 5G++ alocated Java RAM?
> 
> That depends on what other mods you have installed. If you have enough mods to make allocating 5GB necessary I'd recommend using FC in any case, it will probably get it down to 2-3 GB or even less.
> 
> > Also recently there is a mod that claim fix memory leak, is that true?
> 
> I haven't heard about this mod, so I can't answer that.
> 
> > And how related with FerriteCore either already did same thing or need both
> 
> FC does not fix any memory leaks since I'm not aware of any (relevant) ones; so you should probably use both, assuming that the leak fix mod actually fixes a relevant leak.

Thanks or the quick answer, it heleped me figure out thing. I will keep using Ferrite Core and increase ram to 6g.
