### ISSUE TITLE
FerritCore causes Radon, Radium Reforged, and Oculus to not work.

### ISSUE THREAD

**Issue by Zelioth** [malte0811/FerriteCore#96]
Recently started testing ways to improve FPS and performance for clients on my mod pack Friends United. 

Going through every mod i discovered for some odd reason if you have ferriteCore and Radium Reforged, Radon, Rubidium, and Oculus installed the client just will not even launch after the Minecraft client menu that you press Play to start minecraft. 

I am not sure why and the logs do not really indicate anything but you can reproduce simply by making a 1.19.2 back, any version of forge and add ferriteCore and Rubidium and any of it's addons. I understand this MAY not be a ferriteCore only issue or may be something the creator of Rubidium needs to fix but I am reporting it to BOTH mod creators to make sure it's addressed. Only because as a pack developer I would love to keep your mod in the pack and be able to use Rubidium. 

Information 
Minecraft 1.19.2
Forge Any Version of Forge
Ferrite Core 5.0.1 but all released are same issue.
Rubidium and addons. Any Versions

**Comment by Zelioth** [comment]
Update. It doesn't even produce a log if the combined mods are active. If you disable one or the other aka FerriteCore, and or Rubidium and addons it will launch fine

**Comment by Zelioth** [comment]
Log with all mods active 
[latest.log](https://github.com/malte0811/FerriteCore/files/9781831/latest.log)
[debug.log](https://github.com/malte0811/FerriteCore/files/9781832/debug.log)

**Comment by malte0811** [comment]
The problem here is Radium, one of their changes is incompatible with one of FCs. On Fabric (with Lithium) I solve this by specifying that Lithium should not apply that change (since my version is more effective). Radium [intentionally](https://github.com/Asek3/Radium/blob/76cac18f8815da63adfed65e4eef7dafb7cab644/src/main/java/me/jellysquid/mods/lithium/common/config/LithiumConfig.java#L255) removed that possibility. Instead they disable the feature when they detect that FC is installed, but that change was made a few days *after* the latest build on CurseForge was released. So it won't work "out of the box" until @Asek3 publishes a new release of Radium. For now you can add `mixin.alloc.blockstate=false` to `config/radium.properties`.

**Comment by SiverDX** [comment]
Just as a headsup: This issue can occur when you are missing a dependency

It happened for me when I had https://www.curseforge.com/minecraft/mc-mods/advancement-plaques but not its dependency https://www.curseforge.com/minecraft/mc-mods/iceberg

so if anyone has this problem I recommend checking your dependencies too
(In the error log was no mention of any missing dependencies which was the confusing part)

**Comment by K-4U** [comment]
As a heads up to people trying this solution and it not working.
There's also the chance that a mod called Canary is causing the same issue.
The solution provided by @malte0811 does still work, however the file you need to do it in is different: `config/canary.properties`
